//! Generate each crate's README from its rustdoc, for crates.io and GitHub.
//!
//! The crates carry thorough `///` and `//!` documentation. This turns each crate's lib.rs
//! overview and the items it defines into a committed `README.md` in the crate directory -
//! the crates.io page and the crate's landing doc - with registry buttons at the top. It
//! parses the source with `syn` (no nightly needed), so it runs on the scoop toolchain.
//! `cargo xtask docs` regenerates the READMEs; `cargo xtask docs --check` re-generates in
//! memory and fails if a committed README is stale, the way the dashboard i18n bundles are
//! guarded. A hand-written crate README (the dashboard's) is detected by the absence of the
//! generated marker and left untouched. It also writes `docs/README.md`, a one-file API index
//! that links each crate's README (which in turn buttons through to docs.rs).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use quote::ToTokens;
use syn::{Fields, ImplItem, Item, TraitItem, Visibility};

/// Run the `docs` task: regenerate the crate READMEs, or `--check` to verify they are in sync.
///
/// # Arguments
///
/// * `args` - `--check` verifies without writing; otherwise the READMEs are regenerated.
///
/// # Returns
///
/// Success when the READMEs were written, or when the check found them in sync.
pub fn run(args: &[String]) -> ExitCode {
    let check = args.iter().any(|arg| arg == "--check");
    match render_all() {
        Ok(readmes) => {
            let ok = if check {
                verify_crate_readmes(&readmes)
            } else {
                write_crate_readmes(&readmes)
            };
            if ok {
                ExitCode::SUCCESS
            } else {
                ExitCode::FAILURE
            }
        }
        Err(message) => {
            eprintln!("xtask docs: {message}");
            ExitCode::FAILURE
        }
    }
}

// The leading marker on a generated crate README; a README without it is hand-written (the
// dashboard's), so the generator leaves it alone.
const GEN_MARKER: &str = "<!-- Generated by `cargo xtask docs` from this crate's lib.rs; edit the crate doc, not this file. -->";

// Reads a crate's one-line `description` from its Cargo.toml, if present.
fn crate_description(krate: &str) -> Option<String> {
    let toml =
        fs::read_to_string(repo_root().join("crates").join(krate).join("Cargo.toml")).ok()?;
    for line in toml.lines() {
        if let Some(rest) = line.trim_start().strip_prefix("description") {
            if let Some(value) = rest.trim_start().strip_prefix('=') {
                let value = value.trim().trim_matches('"').trim();
                if !value.is_empty() {
                    return Some(value.to_owned());
                }
            }
        }
    }
    None
}

// The crates that also ship language bindings, with their package id on (npm, PyPI, NuGet),
// so the README links the registries that actually have the crate.
fn bindings(krate: &str) -> Option<(&'static str, &'static str, &'static str)> {
    match krate {
        "pamoja-core" => Some(("@pamoja/core", "pamoja-core", "Pamoja.Core")),
        _ => None,
    }
}

// One gradient button linking a registry, as inline HTML (renders on crates.io and GitHub).
fn button(href: &str, alt: &str, file: &str) -> String {
    format!(
        "<a href=\"{href}\"><img height=\"28\" alt=\"{alt}\" src=\"https://raw.githubusercontent.com/molexxxx/pamoja/main/.github/badges/{file}\"></a>"
    )
}

// The single per-crate README - the crates.io page and the crate's doc landing in one file:
// name, description, registry buttons, the lib.rs overview, and the items lib.rs defines. The
// full per-module API reference is docs.rs (linked by the buttons).
fn crate_readme(krate: &str, overview: &str, items: &str) -> String {
    let mut out = format!("{GEN_MARKER}\n\n# {krate}\n\n");
    if let Some(description) = crate_description(krate) {
        out.push_str(&description);
        out.push_str("\n\n");
    }
    let mut buttons = vec![
        button(
            &format!("https://crates.io/crates/{krate}"),
            "crates.io",
            "btn-cratesio.svg",
        ),
        button(
            &format!("https://docs.rs/{krate}"),
            "docs.rs",
            "btn-docsrs.svg",
        ),
    ];
    if let Some((npm, pypi, nuget)) = bindings(krate) {
        buttons.push(button(
            &format!("https://www.npmjs.com/package/{npm}"),
            "npm",
            "btn-npm.svg",
        ));
        buttons.push(button(
            &format!("https://pypi.org/project/{pypi}/"),
            "PyPI",
            "btn-pypi.svg",
        ));
        buttons.push(button(
            &format!("https://www.nuget.org/packages/{nuget}"),
            "NuGet",
            "btn-nuget.svg",
        ));
    }
    out.push_str(&buttons.join("\n"));
    out.push_str("\n\n");
    if !overview.is_empty() {
        out.push_str(overview);
        out.push_str("\n\n");
    }
    out.push_str(items);
    out.push_str("## License\n\nMIT - part of the [pamoja](https://github.com/molexxxx/pamoja) workspace: one memory-safe Rust core with bindings for every language.\n");
    out
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("repo root is two levels above the xtask crate")
        .to_path_buf()
}

// The workspace library crates (a `crates/<name>/src/lib.rs`), sorted; binaries like xtask
// have no lib and are skipped.
fn lib_crates() -> Result<Vec<String>, String> {
    let dir = repo_root().join("crates");
    let mut names: Vec<String> = fs::read_dir(&dir)
        .map_err(|e| format!("reading {}: {e}", dir.display()))?
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.join("src/lib.rs").is_file())
        .filter_map(|path| path.file_name().and_then(|n| n.to_str()).map(str::to_owned))
        .collect();
    names.sort();
    Ok(names)
}

// Renders the per-crate READMEs plus a top API index (a TOC linking each crate's README),
// as (path, contents).
fn render_all() -> Result<Vec<(String, String)>, String> {
    let crates_root = repo_root().join("crates");
    let crates = lib_crates()?;
    let mut readmes = Vec::new();
    let mut index = format!(
        "{GEN_MARKER}\n\n# API reference\n\nEach crate's README is its overview, examples, and crates.io page, with a button to the full per-item API on docs.rs. This index links them all.\n\n## Crates\n\n"
    );

    for krate in &crates {
        let lib = fs::read_to_string(crates_root.join(krate).join("src/lib.rs"))
            .map_err(|e| format!("reading {krate}/lib.rs: {e}"))?;
        let lib_parsed =
            syn::parse_file(&lib).map_err(|e| format!("parsing {krate}/lib.rs: {e}"))?;
        let overview = doc_of(&lib_parsed.attrs);
        let items = render_items(&lib_parsed.items);
        readmes.push((
            format!("crates/{krate}/README.md"),
            crate_readme(krate, &overview, &items),
        ));
        // Anchor the link to the crate README's title heading, so it opens at the top.
        match crate_description(krate) {
            Some(desc) => index.push_str(&format!(
                "- [{krate}](../crates/{krate}/README.md#{krate}) - {desc}\n"
            )),
            None => index.push_str(&format!(
                "- [{krate}](../crates/{krate}/README.md#{krate})\n"
            )),
        }
    }
    readmes.push(("docs/README.md".to_owned(), index));
    Ok(readmes)
}

// Renders the public items of lib.rs to Markdown, in source order.
fn render_items(items: &[Item]) -> String {
    let mut out = String::new();
    for item in items {
        match item {
            Item::Struct(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "struct",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                fields(&mut out, &item.fields);
            }
            Item::Enum(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "enum",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                for variant in &item.variants {
                    let doc = doc_of(&variant.attrs);
                    out.push_str(&format!("- `{}`", variant.ident));
                    if !doc.is_empty() {
                        out.push_str(&format!(" - {}", doc.replace('\n', " ")));
                    }
                    out.push('\n');
                }
                out.push('\n');
            }
            Item::Trait(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "trait",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                for trait_item in &item.items {
                    if let TraitItem::Fn(method) = trait_item {
                        member(
                            &mut out,
                            &tidy(method.sig.to_token_stream().to_string()),
                            &doc_of(&method.attrs),
                        );
                    }
                }
            }
            Item::Fn(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "fn",
                    &item.sig.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                code(&mut out, &tidy(item.sig.to_token_stream().to_string()));
            }
            Item::Const(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "const",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                code(
                    &mut out,
                    &tidy(format!(
                        "const {}: {}",
                        item.ident,
                        item.ty.to_token_stream()
                    )),
                );
            }
            Item::Type(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "type",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
            }
            // Inherent impls contribute their public methods under the type.
            Item::Impl(item) if item.trait_.is_none() => {
                let ty = tidy(item.self_ty.to_token_stream().to_string());
                for impl_item in &item.items {
                    if let ImplItem::Fn(method) = impl_item {
                        if is_public(&method.vis) {
                            out.push_str(&format!("### `{ty}::{}`\n\n", method.sig.ident));
                            let doc = doc_of(&method.attrs);
                            if !doc.is_empty() {
                                out.push_str(&doc);
                                out.push_str("\n\n");
                            }
                            code(&mut out, &tidy(method.sig.to_token_stream().to_string()));
                        }
                    }
                }
            }
            _ => {}
        }
    }
    out
}

fn section(out: &mut String, kind: &str, name: &str, doc: &str) {
    out.push_str(&format!("## {kind} `{name}`\n\n"));
    if !doc.is_empty() {
        out.push_str(doc);
        out.push_str("\n\n");
    }
}

fn member(out: &mut String, sig: &str, doc: &str) {
    out.push_str(&format!("### `{sig}`\n\n"));
    if !doc.is_empty() {
        out.push_str(doc);
        out.push_str("\n\n");
    }
}

fn code(out: &mut String, text: &str) {
    out.push_str(&format!("```rust\n{text}\n```\n\n"));
}

fn fields(out: &mut String, fields: &Fields) {
    if let Fields::Named(named) = fields {
        let public: Vec<_> = named.named.iter().filter(|f| is_public(&f.vis)).collect();
        if public.is_empty() {
            return;
        }
        out.push_str("Fields:\n\n");
        for field in public {
            let name = field
                .ident
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default();
            let ty = tidy(field.ty.to_token_stream().to_string());
            let doc = doc_of(&field.attrs);
            out.push_str(&format!("- `{name}: {ty}`"));
            if !doc.is_empty() {
                out.push_str(&format!(" - {}", doc.replace('\n', " ")));
            }
            out.push('\n');
        }
        out.push('\n');
    }
}

fn is_public(vis: &Visibility) -> bool {
    matches!(vis, Visibility::Public(_))
}

// Whether a rustdoc code-fence info string denotes a Rust block: empty (rustdoc's default) or
// only Rust fence attributes. An explicit other language (`text`, `toml`, `sh`) is left alone.
fn is_rust_fence(info: &str) -> bool {
    info.is_empty()
        || info.split(',').all(|token| {
            matches!(
                token.trim(),
                "rust"
                    | "no_run"
                    | "ignore"
                    | "should_panic"
                    | "compile_fail"
                    | "edition2015"
                    | "edition2018"
                    | "edition2021"
                    | "edition2024"
            )
        })
}

// The rustdoc section headers that would otherwise render as top-level Markdown headings.
const SECTIONS: &[&str] = &[
    "# Arguments",
    "# Returns",
    "# Errors",
    "# Examples",
    "# Panics",
    "# Safety",
];

// Joins an item's `///`/`//!` doc lines (dropping the single leading space rustdoc adds) and
// renders them as Markdown: rustdoc section headers become bold labels rather than H1s, and
// hidden doctest lines (`#` inside a code fence) are dropped, with `##` unescaped to `#`.
fn doc_of(attrs: &[syn::Attribute]) -> String {
    let mut raw = Vec::new();
    for attr in attrs {
        if attr.path().is_ident("doc") {
            if let syn::Meta::NameValue(nv) = &attr.meta {
                if let syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(text),
                    ..
                }) = &nv.value
                {
                    let line = text.value();
                    raw.push(line.strip_prefix(' ').unwrap_or(&line).to_owned());
                }
            }
        }
    }

    let mut out = Vec::new();
    let mut in_fence = false;
    for line in raw {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") {
            let opening = !in_fence;
            in_fence = !in_fence;
            // rustdoc's bare (and `no_run`/`ignore`/...) fences are Rust, so tag the opening
            // fence as `rust` for highlighting; keep an explicit other language (text, toml).
            let info = trimmed.trim_start_matches('`').trim();
            if opening && is_rust_fence(info) {
                let indent = &line[..line.len() - trimmed.len()];
                out.push(format!("{indent}```rust"));
            } else {
                out.push(line);
            }
        } else if in_fence {
            if trimmed == "#" || trimmed.starts_with("# ") {
                continue; // a hidden doctest line
            }
            match trimmed.strip_prefix("##") {
                Some(rest) => out.push(format!("#{rest}")),
                None => out.push(line),
            }
        } else if SECTIONS.contains(&line.as_str()) {
            out.push(format!("**{}**", &line[2..]));
        } else {
            out.push(line);
        }
    }
    out.join("\n").trim_end().to_owned()
}

// Tidies a token-stream-rendered signature so it reads like source, not spaced tokens.
fn tidy(sig: String) -> String {
    sig.replace(" ::", "::")
        .replace(":: ", "::")
        .replace(" :", ":")
        .replace("< ", "<")
        .replace(" >", ">")
        .replace(" ,", ",")
        .replace(" (", "(")
        .replace("( ", "(")
        .replace(" )", ")")
        .replace("& ", "&")
        .replace("  ", " ")
}

// Whether a crate README on disk is hand-written (so the generator must not touch it).
fn is_handwritten(path: &Path) -> bool {
    match fs::read_to_string(path) {
        Ok(text) => !text.contains(GEN_MARKER),
        Err(_) => false,
    }
}

// Writes the per-crate READMEs, leaving any hand-written one (no marker) in place.
fn write_crate_readmes(readmes: &[(String, String)]) -> bool {
    let base = repo_root();
    let mut written = 0;
    for (name, body) in readmes {
        let path = base.join(name);
        if path.exists() && is_handwritten(&path) {
            continue;
        }
        if let Some(parent) = path.parent() {
            if let Err(err) = fs::create_dir_all(parent) {
                eprintln!("xtask docs: creating {}: {err}", parent.display());
                return false;
            }
        }
        if let Err(err) = fs::write(&path, body) {
            eprintln!("xtask docs: writing {}: {err}", path.display());
            return false;
        }
        written += 1;
    }
    println!("docs: wrote {written} files (crate READMEs + API index; hand-written ones kept)");
    true
}

// Verifies the generated crate READMEs are in sync, skipping any hand-written one.
fn verify_crate_readmes(readmes: &[(String, String)]) -> bool {
    let base = repo_root();
    let mut stale = Vec::new();
    for (name, body) in readmes {
        let path = base.join(name);
        if path.exists() && is_handwritten(&path) {
            continue;
        }
        match fs::read_to_string(&path) {
            Ok(on_disk) if &on_disk == body => {}
            _ => stale.push(name.clone()),
        }
    }
    if stale.is_empty() {
        println!("docs: crate READMEs are in sync");
        true
    } else {
        eprintln!(
            "xtask docs: stale or missing crate READMEs: {}\n  run `cargo xtask docs` and commit the result",
            stale.join(", ")
        );
        false
    }
}
