//! Generate scoped Markdown API docs for the workspace crates from their rustdoc comments.
//!
//! The crates carry thorough `///` and `//!` documentation; this turns that into committed,
//! browsable Markdown under a single root `docs/` hub - one folder per crate, one file per
//! module, plus an index - so the whole API is readable on GitHub without building rustdoc
//! HTML. It parses the source with `syn` (no nightly needed), so it runs on the scoop
//! toolchain. `cargo xtask docs` regenerates the tree; `cargo xtask docs --check`
//! re-generates in memory and fails if the committed docs are stale, the way the dashboard
//! i18n bundles are guarded. It also writes a short `README.md` into each crate (its title,
//! links, and lib.rs overview) so crates.io has a readme without shipping the whole hub; a
//! hand-written crate README (the dashboard's) is detected by the absence of the generated
//! marker and left untouched. The canonical per-crate API stays on docs.rs.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use quote::ToTokens;
use syn::{Fields, ImplItem, Item, TraitItem, Visibility};

/// Where the generated docs live, relative to the repo root.
const DOCS_DIR: &str = "docs";

/// The rendered output: the docs-hub files and the per-crate READMEs, each a list of
/// (relative path, contents).
type Rendered = (Vec<(String, String)>, Vec<(String, String)>);

/// Run the `docs` task: generate the API Markdown, or `--check` to verify it is in sync.
///
/// # Arguments
///
/// * `args` - `--check` verifies without writing; otherwise the docs are regenerated.
///
/// # Returns
///
/// Success when the docs were written, or when the check found them in sync.
pub fn run(args: &[String]) -> ExitCode {
    let check = args.iter().any(|arg| arg == "--check");
    match render_all() {
        Ok((docs, readmes)) => {
            let ok = if check {
                verify(&docs) & verify_crate_readmes(&readmes)
            } else {
                write(&docs) & write_crate_readmes(&readmes)
            };
            if ok {
                ExitCode::SUCCESS
            } else {
                ExitCode::FAILURE
            }
        }
        Err(message) => {
            eprintln!("xtask docs: {message}");
            ExitCode::FAILURE
        }
    }
}

// The leading marker on a generated crate README; a README without it is hand-written (the
// dashboard's), so the generator leaves it alone.
const GEN_MARKER: &str = "<!-- Generated by `cargo xtask docs` from this crate's lib.rs; edit the crate doc, not this file. -->";

// Reads a crate's one-line `description` from its Cargo.toml, if present.
fn crate_description(krate: &str) -> Option<String> {
    let toml =
        fs::read_to_string(repo_root().join("crates").join(krate).join("Cargo.toml")).ok()?;
    for line in toml.lines() {
        if let Some(rest) = line.trim_start().strip_prefix("description") {
            if let Some(value) = rest.trim_start().strip_prefix('=') {
                let value = value.trim().trim_matches('"').trim();
                if !value.is_empty() {
                    return Some(value.to_owned());
                }
            }
        }
    }
    None
}

// The concise crates.io-facing README for a crate: its name, description, links, and the
// lib.rs overview - not the full item dump, which is on docs.rs and in the docs/ hub.
fn crate_readme(krate: &str, overview: &str) -> String {
    let mut out = format!("{GEN_MARKER}\n\n# {krate}\n\n");
    if let Some(description) = crate_description(krate) {
        out.push_str(&description);
        out.push_str("\n\n");
    }
    out.push_str(&format!(
        "[crates.io](https://crates.io/crates/{krate}) · [API docs](https://docs.rs/{krate}) · [repository](https://github.com/molexxxx/pamoja)\n\n"
    ));
    if !overview.is_empty() {
        out.push_str(overview);
        out.push_str("\n\n");
    }
    out.push_str("## License\n\nMIT - part of the [pamoja](https://github.com/molexxxx/pamoja) workspace: one memory-safe Rust core with bindings for every language.\n");
    out
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("repo root is two levels above the xtask crate")
        .to_path_buf()
}

// The workspace library crates (a `crates/<name>/src/lib.rs`), sorted; binaries like xtask
// have no lib and are skipped.
fn lib_crates() -> Result<Vec<String>, String> {
    let dir = repo_root().join("crates");
    let mut names: Vec<String> = fs::read_dir(&dir)
        .map_err(|e| format!("reading {}: {e}", dir.display()))?
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.join("src/lib.rs").is_file())
        .filter_map(|path| path.file_name().and_then(|n| n.to_str()).map(str::to_owned))
        .collect();
    names.sort();
    Ok(names)
}

// Renders every output file as (relative path under DOCS_DIR, contents).
fn render_all() -> Result<Rendered, String> {
    let crates_root = repo_root().join("crates");
    let crates = lib_crates()?;
    let mut files = Vec::new();
    let mut readmes = Vec::new();
    let mut index = String::from("# API reference\n\n");
    index.push_str("Generated from each crate's rustdoc by `cargo xtask docs` - do not edit by hand. The canonical per-crate reference is docs.rs; this hub mirrors the source tree.\n\n## Crates\n\n");

    for krate in &crates {
        let src = crates_root.join(krate).join("src");
        let mut modules = module_files(&src)?;
        modules.sort();

        for module in &modules {
            let source = fs::read_to_string(src.join(format!("{module}.rs")))
                .map_err(|e| format!("reading {krate}/{module}.rs: {e}"))?;
            let parsed = syn::parse_file(&source)
                .map_err(|e| format!("parsing {krate}/{module}.rs: {e}"))?;
            let mut body = format!("# {krate}::{module}\n\n");
            body.push_str(
                "Generated from rustdoc by `cargo xtask docs` - do not edit by hand.\n\n",
            );
            let module_doc = doc_of(&parsed.attrs);
            if !module_doc.is_empty() {
                body.push_str(&module_doc);
                body.push_str("\n\n");
            }
            body.push_str(&render_items(&parsed.items));
            files.push((format!("{krate}/{module}.md"), body));
        }

        // The crate index: the overview from lib.rs, links to each module, and any items
        // lib.rs defines itself.
        let lib = fs::read_to_string(src.join("lib.rs"))
            .map_err(|e| format!("reading {krate}/lib.rs: {e}"))?;
        let lib_parsed =
            syn::parse_file(&lib).map_err(|e| format!("parsing {krate}/lib.rs: {e}"))?;
        let mut crate_index = format!("# {krate}\n\n");
        crate_index
            .push_str("Generated from rustdoc by `cargo xtask docs` - do not edit by hand.\n\n");
        let overview = doc_of(&lib_parsed.attrs);
        readmes.push((
            format!("crates/{krate}/README.md"),
            crate_readme(krate, &overview),
        ));
        if !overview.is_empty() {
            crate_index.push_str(&overview);
            crate_index.push_str("\n\n");
        }
        if !modules.is_empty() {
            crate_index.push_str("## Modules\n\n");
            for module in &modules {
                crate_index.push_str(&format!("- [{module}]({module}.md)\n"));
            }
            crate_index.push('\n');
        }
        crate_index.push_str(&render_items(&lib_parsed.items));
        files.push((format!("{krate}/README.md"), crate_index));

        index.push_str(&format!("- [{krate}]({krate}/README.md)\n"));
    }

    files.push(("README.md".to_owned(), index));
    Ok((files, readmes))
}

// The top-level module source files of a crate (`src/*.rs` except lib.rs and main.rs).
fn module_files(src: &Path) -> Result<Vec<String>, String> {
    Ok(fs::read_dir(src)
        .map_err(|e| format!("reading {}: {e}", src.display()))?
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.extension().and_then(|e| e.to_str()) == Some("rs"))
        .filter_map(|path| path.file_stem().and_then(|s| s.to_str()).map(str::to_owned))
        .filter(|name| name != "lib" && name != "main")
        .collect())
}

// Renders the public items of a module (or lib.rs) to Markdown, in source order.
fn render_items(items: &[Item]) -> String {
    let mut out = String::new();
    for item in items {
        match item {
            Item::Struct(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "struct",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                fields(&mut out, &item.fields);
            }
            Item::Enum(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "enum",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                for variant in &item.variants {
                    let doc = doc_of(&variant.attrs);
                    out.push_str(&format!("- `{}`", variant.ident));
                    if !doc.is_empty() {
                        out.push_str(&format!(" - {}", doc.replace('\n', " ")));
                    }
                    out.push('\n');
                }
                out.push('\n');
            }
            Item::Trait(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "trait",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                for trait_item in &item.items {
                    if let TraitItem::Fn(method) = trait_item {
                        member(
                            &mut out,
                            &tidy(method.sig.to_token_stream().to_string()),
                            &doc_of(&method.attrs),
                        );
                    }
                }
            }
            Item::Fn(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "fn",
                    &item.sig.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                code(&mut out, &tidy(item.sig.to_token_stream().to_string()));
            }
            Item::Const(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "const",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
                code(
                    &mut out,
                    &tidy(format!(
                        "const {}: {}",
                        item.ident,
                        item.ty.to_token_stream()
                    )),
                );
            }
            Item::Type(item) if is_public(&item.vis) => {
                section(
                    &mut out,
                    "type",
                    &item.ident.to_string(),
                    &doc_of(&item.attrs),
                );
            }
            // Inherent impls contribute their public methods under the type.
            Item::Impl(item) if item.trait_.is_none() => {
                let ty = tidy(item.self_ty.to_token_stream().to_string());
                for impl_item in &item.items {
                    if let ImplItem::Fn(method) = impl_item {
                        if is_public(&method.vis) {
                            out.push_str(&format!("### `{ty}::{}`\n\n", method.sig.ident));
                            let doc = doc_of(&method.attrs);
                            if !doc.is_empty() {
                                out.push_str(&doc);
                                out.push_str("\n\n");
                            }
                            code(&mut out, &tidy(method.sig.to_token_stream().to_string()));
                        }
                    }
                }
            }
            _ => {}
        }
    }
    out
}

fn section(out: &mut String, kind: &str, name: &str, doc: &str) {
    out.push_str(&format!("## {kind} `{name}`\n\n"));
    if !doc.is_empty() {
        out.push_str(doc);
        out.push_str("\n\n");
    }
}

fn member(out: &mut String, sig: &str, doc: &str) {
    out.push_str(&format!("### `{sig}`\n\n"));
    if !doc.is_empty() {
        out.push_str(doc);
        out.push_str("\n\n");
    }
}

fn code(out: &mut String, text: &str) {
    out.push_str(&format!("```rust\n{text}\n```\n\n"));
}

fn fields(out: &mut String, fields: &Fields) {
    if let Fields::Named(named) = fields {
        let public: Vec<_> = named.named.iter().filter(|f| is_public(&f.vis)).collect();
        if public.is_empty() {
            return;
        }
        out.push_str("Fields:\n\n");
        for field in public {
            let name = field
                .ident
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default();
            let ty = tidy(field.ty.to_token_stream().to_string());
            let doc = doc_of(&field.attrs);
            out.push_str(&format!("- `{name}: {ty}`"));
            if !doc.is_empty() {
                out.push_str(&format!(" - {}", doc.replace('\n', " ")));
            }
            out.push('\n');
        }
        out.push('\n');
    }
}

fn is_public(vis: &Visibility) -> bool {
    matches!(vis, Visibility::Public(_))
}

// The rustdoc section headers that would otherwise render as top-level Markdown headings.
const SECTIONS: &[&str] = &[
    "# Arguments",
    "# Returns",
    "# Errors",
    "# Examples",
    "# Panics",
    "# Safety",
];

// Joins an item's `///`/`//!` doc lines (dropping the single leading space rustdoc adds) and
// renders them as Markdown: rustdoc section headers become bold labels rather than H1s, and
// hidden doctest lines (`#` inside a code fence) are dropped, with `##` unescaped to `#`.
fn doc_of(attrs: &[syn::Attribute]) -> String {
    let mut raw = Vec::new();
    for attr in attrs {
        if attr.path().is_ident("doc") {
            if let syn::Meta::NameValue(nv) = &attr.meta {
                if let syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(text),
                    ..
                }) = &nv.value
                {
                    let line = text.value();
                    raw.push(line.strip_prefix(' ').unwrap_or(&line).to_owned());
                }
            }
        }
    }

    let mut out = Vec::new();
    let mut in_fence = false;
    for line in raw {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") {
            in_fence = !in_fence;
            out.push(line);
        } else if in_fence {
            if trimmed == "#" || trimmed.starts_with("# ") {
                continue; // a hidden doctest line
            }
            match trimmed.strip_prefix("##") {
                Some(rest) => out.push(format!("#{rest}")),
                None => out.push(line),
            }
        } else if SECTIONS.contains(&line.as_str()) {
            out.push(format!("**{}**", &line[2..]));
        } else {
            out.push(line);
        }
    }
    out.join("\n").trim_end().to_owned()
}

// Tidies a token-stream-rendered signature so it reads like source, not spaced tokens.
fn tidy(sig: String) -> String {
    sig.replace(" ::", "::")
        .replace(":: ", "::")
        .replace(" :", ":")
        .replace("< ", "<")
        .replace(" >", ">")
        .replace(" ,", ",")
        .replace(" (", "(")
        .replace("( ", "(")
        .replace(" )", ")")
        .replace("& ", "&")
        .replace("  ", " ")
}

fn write(files: &[(String, String)]) -> bool {
    let base = repo_root().join(DOCS_DIR);
    for (name, body) in files {
        let path = base.join(name);
        if let Some(parent) = path.parent() {
            if let Err(err) = fs::create_dir_all(parent) {
                eprintln!("xtask docs: creating {}: {err}", parent.display());
                return false;
            }
        }
        if let Err(err) = fs::write(&path, body) {
            eprintln!("xtask docs: writing {}: {err}", path.display());
            return false;
        }
    }
    println!("docs: wrote {} files under {DOCS_DIR}/", files.len());
    true
}

fn verify(files: &[(String, String)]) -> bool {
    let base = repo_root().join(DOCS_DIR);
    let mut stale = Vec::new();
    for (name, body) in files {
        match fs::read_to_string(base.join(name)) {
            Ok(on_disk) if &on_disk == body => {}
            _ => stale.push(name.clone()),
        }
    }
    if stale.is_empty() {
        println!("docs: API Markdown is in sync ({} files)", files.len());
        true
    } else {
        eprintln!(
            "xtask docs: stale or missing: {}\n  run `cargo xtask docs` and commit the result",
            stale.join(", ")
        );
        false
    }
}

// Whether a crate README on disk is hand-written (so the generator must not touch it).
fn is_handwritten(path: &Path) -> bool {
    match fs::read_to_string(path) {
        Ok(text) => !text.contains(GEN_MARKER),
        Err(_) => false,
    }
}

// Writes the per-crate crates.io READMEs, leaving any hand-written one (no marker) in place.
fn write_crate_readmes(readmes: &[(String, String)]) -> bool {
    let base = repo_root();
    let mut written = 0;
    for (name, body) in readmes {
        let path = base.join(name);
        if path.exists() && is_handwritten(&path) {
            continue;
        }
        if let Err(err) = fs::write(&path, body) {
            eprintln!("xtask docs: writing {}: {err}", path.display());
            return false;
        }
        written += 1;
    }
    println!("docs: wrote {written} crate READMEs (hand-written ones kept)");
    true
}

// Verifies the generated crate READMEs are in sync, skipping any hand-written one.
fn verify_crate_readmes(readmes: &[(String, String)]) -> bool {
    let base = repo_root();
    let mut stale = Vec::new();
    for (name, body) in readmes {
        let path = base.join(name);
        if path.exists() && is_handwritten(&path) {
            continue;
        }
        match fs::read_to_string(&path) {
            Ok(on_disk) if &on_disk == body => {}
            _ => stale.push(name.clone()),
        }
    }
    if stale.is_empty() {
        println!("docs: crate READMEs are in sync");
        true
    } else {
        eprintln!(
            "xtask docs: stale or missing crate READMEs: {}\n  run `cargo xtask docs` and commit the result",
            stale.join(", ")
        );
        false
    }
}
