# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "MqttClient",
    "MqttMessage",
    "version",
]

@typing.final
class MqttClient:
    r"""
    An MQTT client transport backed by the native pamoja core.
    """
    def __new__(cls, *, client_id: builtins.str, host: builtins.str, port: builtins.int, keep_alive_secs: typing.Optional[builtins.int] = None, capacity: typing.Optional[builtins.int] = None, qos: typing.Optional[builtins.str] = None) -> MqttClient:
        r"""
        Creates a disconnected client from the given options.
        """
    def connect(self) -> typing.Any:
        r"""
        Connects to the broker and starts the background event loop.
        """
    def publish(self, topic: builtins.str, payload: typing.Sequence[builtins.int]) -> typing.Any:
        r"""
        Publishes a payload to a topic.
        """
    def subscribe(self, topic: builtins.str) -> typing.Any:
        r"""
        Subscribes to a topic filter.
        """
    def recv(self) -> typing.Any:
        r"""
        Awaits the next message from any subscribed topic, or `None` once the
        connection has ended.
        """
    def is_connected(self) -> typing.Any:
        r"""
        Reports whether the client currently holds an active connection.
        """
    def disconnect(self) -> typing.Any:
        r"""
        Closes the connection and stops the background event loop.
        """

@typing.final
class MqttMessage:
    r"""
    A message received from a subscribed topic.
    """
    @property
    def topic(self) -> builtins.str:
        r"""
        The topic the message was published to.
        """
    @property
    def payload(self) -> bytes:
        r"""
        The raw payload bytes.
        """
    def __repr__(self) -> builtins.str: ...

def version() -> builtins.str:
    r"""
    Returns the version of the native pamoja module.
    """

